# Generated by Django 6.0.1 on 2026-01-24 05:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriesCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name for the category', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BikeBrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255, unique=True)),
                ('brand_image', models.ImageField(upload_to='bike_brand_images/')),
                ('brand_description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BikeCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='_images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BikeColorsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=255, unique=True)),
                ('color_code', models.CharField(help_text='Enter the first color code in hex format (e.g. #FF0000 for red)', max_length=7)),
                ('color_code_2', models.CharField(blank=True, help_text='Enter the second color if its dual color', max_length=7, null=True)),
                ('color_image', models.ImageField(blank=True, help_text='Upload the color image for the color', null=True, upload_to='bike_color_images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuideAndTrainerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name for the guide and trainer', max_length=255)),
                ('description', models.TextField(help_text='Enter the description for the guide and trainer')),
                ('type', models.CharField(choices=[('guide', 'Guide'), ('trainer', 'Trainer')], default='guide', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSliderVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desktop_video', models.FileField(blank=True, help_text='Upload home slider video', null=True, upload_to='home_slider_videos/')),
                ('mobile_video', models.FileField(blank=True, help_text='Upload home slider video', null=True, upload_to='home_slider_videos/')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RearSuspensionTravelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rear_suspension_travel', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResetPasswordOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuspensionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspension', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WheelSizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheel_size', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessoriesSubCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name for the accessory', max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='Application.accessoriescategorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='AccessoriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Enter the name for the accessory', max_length=255)),
                ('description', models.TextField(help_text='Enter the description for the accessory')),
                ('product_type', models.CharField(default='accessories', editable=False, max_length=255)),
                ('is_dark', models.BooleanField(default=False, help_text='Set true if the accessory is dark')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price for the accessory', max_digits=10)),
                ('is_discount', models.BooleanField(default=False)),
                ('discount_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='Application.accessoriessubcategorymodel')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='Application.bikebrandmodel')),
                ('special_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.specialtagmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accessory_images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_images', to='Application.accessoriesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='BikeImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bike_images_colors/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_images', to='Application.bikecolorsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='BikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('product_type', models.CharField(default='bike', editable=False, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_discount', models.BooleanField(default=False)),
                ('discount_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('background_color', models.CharField(blank=True, help_text='Enter the background color in hex format (e.g. #FF0000 for red)', max_length=255, null=True)),
                ('text_color', models.CharField(blank=True, help_text='Enter the text color in hex format (e.g. #FFFFFF for white)', max_length=255, null=True)),
                ('is_dark', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False, help_text='Set true if the bike is featured (e.g. home page)')),
                ('featured_image', models.ImageField(blank=True, help_text='Upload the featured image for the bike  if its featured', null=True, upload_to='featured_images/')),
                ('youtube_link', models.TextField(blank=True, help_text='Enter the youtube link for the bike', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.bikebrandmodel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.bikecategorymodel')),
                ('material', models.ManyToManyField(related_name='bake_materials', to='Application.materialmodel')),
                ('rear_suspension_travel', models.ManyToManyField(related_name='bike_rear_suspension_travels', to='Application.rearsuspensiontravelmodel')),
                ('sizes', models.ManyToManyField(blank=True, null=True, related_name='bike_sizes', to='Application.sizemodel')),
                ('special_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.specialtagmodel')),
                ('suspension', models.ManyToManyField(related_name='bike_suspensions', to='Application.suspensionmodel')),
                ('wheel_size', models.ManyToManyField(related_name='bike_wheel_sizes', to='Application.wheelsizemodel')),
            ],
        ),
        migrations.CreateModel(
            name='BikeDownloadsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bike_downloads/')),
                ('title', models.CharField(help_text='Enter the title for the download (e.g. Bike Manuel, Bike Brochure, etc)', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_downloads', to='Application.bikemodel')),
            ],
        ),
        migrations.AddField(
            model_name='bikecolorsmodel',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_colors', to='Application.bikemodel'),
        ),
        migrations.CreateModel(
            name='BikePostersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(upload_to='bike_posters/')),
                ('title', models.CharField(help_text='Enter the title for the poster (e.g. Bike Poster, Bike Wallpaper, etc)', max_length=255)),
                ('description', models.TextField(help_text='Enter the description for the poster')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_posters', to='Application.bikemodel')),
            ],
        ),
        migrations.CreateModel(
            name='BikeSpecLabelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Enter the label for the spec (e.g.frameset, component, etc)', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_spec_labels', to='Application.bikemodel')),
            ],
        ),
        migrations.CreateModel(
            name='BikeSpecValueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name for the spec (e.g. front suspension, rear suspension, etc)', max_length=255)),
                ('value', models.CharField(help_text='Enter the value for the spec (e.g. front suspension, rear suspension, etc)', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bike_spec_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_spec_values', to='Application.bikespeclabelmodel')),
            ],
        ),
        migrations.AddField(
            model_name='bikecolorsmodel',
            name='color',
            field=models.ForeignKey(help_text='select the color for the image', on_delete=django.db.models.deletion.CASCADE, related_name='bike_colors', to='Application.colormodel'),
        ),
        migrations.CreateModel(
            name='BikeSizesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_sizes', to='Application.bikemodel')),
                ('bike_size', models.ForeignKey(help_text='select the size for the bike', on_delete=django.db.models.deletion.CASCADE, to='Application.sizemodel')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BikeReviewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(help_text='Enter the review for the bike')),
                ('rating', models.IntegerField(help_text='Enter the rating for the bike')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_reviews', to='Application.bikemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
