# Generated by Django 6.0.1 on 2026-01-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriesmodel',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accessoriesmodel',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='is_out_of_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
