# Generated by Django 6.0.1 on 2026-01-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_accessoriesmodel_is_available_accessoriesmodel_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriesmodel',
            name='is_out_of_stock',
            field=models.BooleanField(default=False),
        ),
    ]
