# Generated by Django 6.0.1 on 2026-01-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_accessoriesmodel_is_out_of_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriescategorymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accessory_category_images/'),
        ),
    ]
