# Generated by Django 6.0.1 on 2026-01-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_accessoriescategorymodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikebrandmodel',
            name='brand_image',
            field=models.ImageField(help_text='Upload the brand image for the brand, this is requiered', upload_to='bike_brand_images/'),
        ),
        migrations.AlterField(
            model_name='bikecategorymodel',
            name='category_image',
            field=models.ImageField(blank=True, help_text='Upload the category image for the category, this is requiered', null=True, upload_to='_images/'),
        ),
    ]
