# Generated by Django 6.0.1 on 2026-01-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_alter_bikebrandmodel_brand_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikebrandmodel',
            name='brand_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
