# Generated by Django 6.0.1 on 2026-04-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_alter_bikebrandmodel_brand_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikebrandmodel',
            name='online_purchase_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='online_purchase_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bikebrandmodel',
            name='brand_image',
            field=models.ImageField(help_text='Upload the brand image for the brand, this is requiered and add png files only', upload_to='bike_brand_images/'),
        ),
    ]
