# Generated by Django 6.0.1 on 2026-04-30 06:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0007_bikebrandmodel_online_purchase_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikemodel',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='bike_sizes', to='Application.sizemodel'),
        ),
        migrations.CreateModel(
            name='UserCartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_products', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_bikes', models.IntegerField(default=0)),
                ('total_accessories', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCartItemsModelBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_items', to='Application.bikemodel')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_items', to='Application.bikecolorsmodel')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_items', to='Application.bikesizesmodel')),
                ('user_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_bike_items', to='Application.usercartmodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserCartItemsModelAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_items', to='Application.accessoriesmodel')),
                ('user_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_accessory_items', to='Application.usercartmodel')),
            ],
        ),
    ]
