# Generated by Django 6.0.1 on 2026-04-30 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0008_alter_bikemodel_sizes_usercartmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercartitemsmodelbike',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_items', to='Application.sizemodel'),
        ),
    ]
