# Generated by Django 6.0.1 on 2026-04-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0010_useraddress_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='address_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
