# Generated by Django 6.0.1 on 2026-05-01 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0012_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='accessories',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='bike',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
