# Generated by Django 6.0.1 on 2026-05-01 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0014_userordersmodel_bikeorderitems_accessoriesorderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeorderitems',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bike_orders', to='Application.sizemodel'),
        ),
    ]
