# Generated by Django 6.0.1 on 2026-05-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0015_alter_bikeorderitems_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriesmodel',
            name='online_purchase_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
