# Generated by Django 6.0.1 on 2026-05-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0016_accessoriesmodel_online_purchase_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriesmodel',
            name='shipping_charge',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='shipping_charge',
            field=models.BooleanField(default=True),
        ),
    ]
