# Generated by Django 6.0.1 on 2026-05-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0017_accessoriesmodel_shipping_charge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingChargeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bike', 'bike'), ('accessory', 'accessory')], default='bike', help_text='Enter the name for the shipping charge', max_length=255, unique=True)),
                ('charge', models.DecimalField(decimal_places=2, help_text='Enter the charge for the shipping', max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
