# Generated by Django 6.0.1 on 2026-05-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0018_shippingchargemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userordersmodel',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
