# Generated by Django 6.0.1 on 2026-05-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0019_userordersmodel_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userordersmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Failed', 'Failed')], default='Pending', max_length=50),
        ),
    ]
