# Generated by Django 6.0.1 on 2026-05-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0020_alter_userordersmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoriesmodel',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bikemodel',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
