# Generated by Django 6.0.1 on 2026-05-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0021_alter_accessoriesmodel_shipping_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
