# Generated by Django 6.0.1 on 2026-05-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0022_alter_useraddress_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userordersmodel',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
