# Generated by Django 6.0.1 on 2026-05-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0023_userordersmodel_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userordersmodel',
            name='deliverd_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userordersmodel',
            name='shipped_via',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userordersmodel',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
