# Generated by Django 6.0.1 on 2026-05-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0026_alter_conatactenquiryusermodel_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConatactEnquiryUserModel',
        ),
    ]
