# Generated by Django 6.0.1 on 2026-05-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0027_delete_conatactenquiryusermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConatactEnquiryModel',
            new_name='ContactEnquiryModel',
        ),
    ]
